"""
Complexity — the Escape sub-process.

MODULES.md:

    COMPLEXITY
    - SYSTEM INSTABILITY (why it changes, why it needs constant
      fight)
    - (Esc) ESCAPE SUB-PROCESS (a state system has in itself a
      degree of instability, or it'd be dead)
    - works (A) by Defect of Functionality or (B) by Excess of
      Functionality
    - Esc = B+/- (or B splits in + and - like a Photon splits in
      an Electron and a Positron)
    - Build complexity over Time, exponentially.

When Logos fracture stays low for too long ('Balance = death of
motion', CONCEPTS.md), Complexity injects a pair of opposing
internal stimuli (B+ and B-) to restart motion. This is the only
module other than AION/IMPULSE allowed to fabricate Stimuli, and
it must always emit the pair — instability is generated by
opposition, never by a single signed nudge.

Subscribes to: LogosTension.
Publishes:     Stimulus(modality='escape:+'),
               Stimulus(modality='escape:-').
"""

from __future__ import annotations

import time

from solaris.modules.base import Module
from solaris.runtime.signals import LogosTension, Stimulus


class Complexity(Module):
    name = "complexity"

    def __init__(
        self,
        conscience,
        low_fracture: float = 0.05,
        dwell: float = 2.0,
    ) -> None:
        super().__init__(conscience)
        self.low_fracture = low_fracture
        self.dwell = dwell
        self._low_since: float | None = None
        self.state = {"escapes": 0, "low_dwell_s": 0.0}

    async def start(self) -> None:
        self.bus.subscribe(LogosTension, self._on_tension)

    async def _on_tension(self, sig: LogosTension) -> None:
        now = time.monotonic()
        if sig.fracture < self.low_fracture:
            if self._low_since is None:
                self._low_since = now
            self.state["low_dwell_s"] = round(now - self._low_since, 2)
            if now - self._low_since >= self.dwell:
                await self._escape()
                self._low_since = None
        else:
            self._low_since = None
            self.state["low_dwell_s"] = 0.0

    async def _escape(self) -> None:
        self.state["escapes"] += 1
        # B+/- pair: emitted together, by definition of Esc.
        await self.bus.publish(Stimulus(
            origin=self.name,
            modality="escape:+",
            payload="instability+",
            intensity=0.6,
        ))
        await self.bus.publish(Stimulus(
            origin=self.name,
            modality="escape:-",
            payload="instability-",
            intensity=0.6,
        ))
