"""
Memory / Senses — memory in the in-between.

MODULES.md:

    Memory occurs 'in-between' — generated by the relation /
    interaction between Brain (which works with electric impulse
    with variable intensity like a neural network) and Senses.

We model memory not as a store kept by either side, but as a ring
of traces that arises only when both Stimulus and Action are
flowing. If only Stimuli arrive (perceiving without acting),
memory is half-formed; if only Actions are emitted (acting without
perception), the same. The full trace requires both — exactly the
'in-between' definition above.

Subscribes to: Stimulus, Action.
Provides:      .recent(n) for other modules to consult.
"""

from __future__ import annotations

from collections import deque
from typing import Any

from solaris.modules.base import Module
from solaris.runtime.signals import Action, Signal, Stimulus


class MemorySenses(Module):
    name = "memory_senses"

    def __init__(self, conscience, capacity: int = 512) -> None:
        super().__init__(conscience)
        self.capacity = capacity
        self.trace: deque[Signal] = deque(maxlen=capacity)
        self.state = {"size": 0, "stimuli": 0, "actions": 0}

    async def start(self) -> None:
        self.bus.subscribe(Stimulus, self._record_stimulus)
        self.bus.subscribe(Action, self._record_action)

    async def _record_stimulus(self, sig: Stimulus) -> None:
        self.trace.append(sig)
        self.state["stimuli"] += 1
        self.state["size"] = len(self.trace)

    async def _record_action(self, sig: Action) -> None:
        self.trace.append(sig)
        self.state["actions"] += 1
        self.state["size"] = len(self.trace)

    def recent(self, n: int = 10) -> list[Signal]:
        return list(self.trace)[-n:]

    def count_recent(self, predicate, n: int = 32) -> int:
        return sum(1 for s in self.recent(n) if predicate(s))
